INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (1, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (2, 'LUCIANO','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (3, 'RAFAEL','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at , foto) VALUES (4, 'JULIETA','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (5, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (6, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (7, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (8, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at , foto) VALUES (9, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (10, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (11, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (12, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (13, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (14, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (15, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (16, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (17, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (18, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (19, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (20, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (21, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (22, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (23, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (24, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (25, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (26, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (27, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES (28, 'AGUSTIN','DECIMA','AGUDECIMA@GMAIL.COM','2018-11-29','')